# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Colin Ganzevoort — Psychology, Research, & Technology
homepage_title: Colin Ganzevoort
homepage_description: Psychology, Research, & Technology
email: website-dnL2LQ@colinganzevoort.nl
description: >- # this means to ignore newlines until "baseurl:"
  I am a Research Master student at the University of Groningen (RUG), specialising in Mental Health and Clinical Psychology. Find more details about me and my work on this website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://colinganzevoort.nl" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.png
twitter_username: colinowg
linkedin_username: colinganzevoort
github_username:  coliinnn
hide_credits: true
hide_search: true
page_excerpts: true

permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:  # Also add these to the Gemfile. Then install with 'bundle'. Github errors? Do `bundle update`.
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-sitemap
  - premonition

paginate: 3
paginate_path: "/page/:num/"
